# Model Parameters
MAX_FEATURES = 10000
MAX_SEQUENCE_LENGTH = 200
EMBEDDING_DIM = 100
BATCH_SIZE = 32
EPOCHS = 20
RANDOM_SEED = 42

# Preprocessing Parameters
REMOVE_STOPWORDS = True
APPLY_LEMMATIZATION = True
HANDLE_NEGATION = True
NGRAM_RANGE = (1, 2)

# Training Parameters
LEARNING_RATE = 0.001
DROPOUT_RATE = 0.5